# Generated by Django 3.2.6 on 2021-10-14 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False)),
                ('from_address', models.CharField(max_length=50)),
                ('from_city', models.CharField(max_length=50)),
                ('from_zip_code', models.CharField(max_length=10)),
                ('from_country', models.CharField(max_length=50)),
                ('client_name', models.CharField(max_length=50)),
                ('client_email', models.EmailField(max_length=50, unique=True)),
                ('client_address', models.CharField(max_length=50)),
                ('client_city', models.CharField(max_length=50)),
                ('client_zip_code', models.CharField(max_length=10)),
                ('client_country', models.CharField(max_length=50)),
                ('invoice_date', models.DateField()),
                ('payment_due_date', models.DateField()),
                ('terms', models.CharField(choices=[('30', '30 days'), ('60', '60 days')], default='', max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending'), ('draft', 'Draft')], default=('paid', 'Paid'), max_length=50)),
                ('total', models.FloatField(default='0.00')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField(default='1')),
                ('price', models.FloatField(default='0.00')),
                ('total', models.FloatField(default='0.00')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoices.invoice')),
            ],
        ),
    ]
