# Generated by Django 3.2.6 on 2021-10-14 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_alter_invoice_terms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending'), ('draft', 'Draft')], default=('pending', 'Pending'), max_length=50),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='terms',
            field=models.CharField(choices=[('30', '30 days'), ('60', '60 days')], default='', max_length=50),
        ),
    ]
