# Generated by Django 3.2.6 on 2021-10-14 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_auto_20211014_0143'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='uid',
            field=models.CharField(default='', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
