# Generated by Django 3.2.6 on 2021-10-14 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_auto_20211014_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='uid',
            field=models.CharField(default='', max_length=50),
        ),
    ]
