# Generated by Django 3.2.6 on 2021-10-14 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_alter_invoice_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='uid',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
